name: deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - run: rsync -avz -e "ssh -o StrictHostKeyChecking=no -l www" _site/ cherf.ais-ucla.org:/www/blog.ais-ucla.org
